### ISSUE TITLE
Copy team members from hopr.swiss to hoprnet.org

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-website#155]
### Introduction

Currently, our team members are listed in hopr.swiss, the AG (i.e. LLC) company supporting the HOPR Association, the non-profit building the protocol. Since this legal structure might not be obvious to users, and it might look as only a few founders are working in HOPR, we want to copy the team members we have in [HOPR Services AG website](https://hopr.swiss/who-is-HOPR#team) to the [HOPR Association website](https://hoprnet.org/who-is-HOPR#about).

### Task Description

- [x] Copy all the team images from the [hopr.swiss repository](https://github.com/hoprnet/website-hopr-swiss) to this repository.
- [x] Create a new section with a subtitle "People building the HOPR Network" under the "About us" page.
- [x] Copy all the team members with their images and names into the website.

**Comment by betinho89** [comment]
Ready in next commit 3d169cd84d8465a63816ad3cf57d7f8b8c557594

**Comment by betinho89** [comment]
Done!
#154

**Comment by kitschbent** [comment]
Add me, pic is attached, thanks @betinho89 

Matthew Edwards

Community Manager

![HOPR_Matthew](https://user-images.githubusercontent.com/34662130/104138879-565ac380-5375-11eb-8bd9-8ca42ab7d39c.jpg)

**Comment by 0xjjpa** [comment]
@betinho89 can you take a look at @kitschbent there?

**Comment by kitschbent** [comment]
I can supply the graphics as-needed. I only have the avatar image, covid
and time didn't allow for a proper photo

**Comment by betinho89** [comment]
Hi @kitschbent , can you please provide the image without background color white?

**Comment by betinho89** [comment]
Ready in the pull request #168
